name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          xcodebuild build -scheme "ConcurrencyPlayground" \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest"
